#!/usr/bin/env python2

'''
Publish a sensor_msgs/Image to a topic.
'''

import rospy
import argparse
import cv2
from sensor_msgs.msg import Image
from cv_bridge import CvBridge

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('topic')
    parser.add_argument('image')
    parser.add_argument('-r', '--rate', type=float, default=60)

    args = parser.parse_args(rospy.myargv()[1:])

    rospy.loginfo('Publishing {0} to {1}'.format(args.image, args.topic))

    cv_image = cv2.imread(args.image, cv2.CV_LOAD_IMAGE_COLOR)

    rospy.init_node('imagepub', anonymous=True)
    pub = rospy.Publisher(args.topic, Image, queue_size=10)

    bridge = CvBridge()
    image = bridge.cv2_to_imgmsg(cv_image, 'bgr8')

    rate = rospy.Rate(args.rate)
    while not rospy.is_shutdown():
        image.header.stamp = rospy.Time.now()
        pub.publish(image)
        rate.sleep()
