#!/usr/bin/env python2

from qtcopter.missions import DiffFind
from qtcopter.missions.balloon.blob_find import find_balloon
from qtcopter.missions import ObjectFindMission

if __name__ == '__main__':
    # Search for color red
    finder = DiffFind((255, 0, 0))
    mission = ObjectFindMission('balloon_mission', finder.find_roi, find_balloon)
    mission.execute()
