#!/usr/bin/env python2

from qtcopter.missions.balldrop.hist_find import find_roi
from qtcopter.missions.balldrop.polarity_find import find_target
from qtcopter.missions import ObjectFindMission

if __name__ == '__main__':
    mission = ObjectFindMission('balldrop_mission', find_roi, find_target)
    mission.execute()
