#!/usr/bin/env python2

from qtcopter.missions import DistanceFind
from qtcopter.missions.balldrop.polarity_find import find_target
from qtcopter.missions import ObjectFindMission

if __name__ == '__main__':
    finder = DistanceFind((200, 200, 200), (255, 255, 255))
    mission = ObjectFindMission('balldrop_mission', finder.find_roi, find_target)
    mission.execute()
