#!/usr/bin/env python2

from qtcopter.missions import DistanceFind
#from qtcopter.missions.balloon.blob_find import find_balloon
from qtcopter.missions import ObjectFindMission


def foo(image):
    return None

if __name__ == '__main__':
    # Search for color red (color ordering is BGR)
    finder = DistanceFind((17, 15, 100), (80, 86, 200))
    mission = ObjectFindMission('balloon_mission', finder.find_roi, foo)
    mission.execute()
